### ISSUE TITLE
trouble fetching address book

### ISSUE THREAD

**Issue by coachshea** [graywolf/gbook#3]
Thanks again for the great product. It's been a great help to me, but for whatever reason every year or two I seem to have an issue pop up. gbook has been working perfectly since my last issue. Now, suddenly, I get the following error message whenever I run it:

17:34:26:ERROR  : contacts       : Cannot find feed element:
<?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>invalid</code>
  <internalReason>Supposed groupUri http://www.google.com/m8/feeds/groups/coachjohnshea@gmail.com/base/6does not match template</internalReason>
 </error>
</errors>
 in /home/coachshea/repositories/gbook/src/contacts.cpp:get_all:69
17:34:26:ERROR  : main           : No feed element: <?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>invalid</code>
  <internalReason>Supposed groupUri http://www.google.com/m8/feeds/groups/coachjohnshea@gmail.com/base/6does not match template</internalReason>
 </error>
</errors>

Sorry to bother you, but any help is greatly appreciated

**Comment by graywolf** [comment]
I'm bit busy at the moment, will have time to look into into over weekend, hopefully it's fast enough for you :)T.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: John SheaSent: Wednesday, December 6, 2017 23:41To: graywolf/gbookReply To: graywolf/gbookCc: SubscribedSubject: [graywolf/gbook] trouble fetching address book (#3)Thanks again for the great product. It's been a great help to me, but for whatever reason every year or two I seem to have an issue pop up. gbook has been working perfectly since my last issue. Now, suddenly, I get the following error message whenever I run it:
17:34:26:ERROR  : contacts       : Cannot find feed element:


 
  GData
  invalid
  Supposed groupUri http://www.google.com/m8/feeds/groups/coachjohnshea@gmail.com/base/6does not match template
 

 in /home/coachshea/repositories/gbook/src/contacts.cpp:get_all:69
17:34:26:ERROR  : main           : No feed element: 

 
  GData
  invalid
  Supposed groupUri http://www.google.com/m8/feeds/groups/coachjohnshea@gmail.com/base/6does not match template
 

Sorry to bother you, but any help is greatly appreciated

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/graywolf/gbook","title":"graywolf/gbook","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/graywolf/gbook"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"trouble fetching address book (#3)"}],"action":{"name":"View Issue","url":"https://github.com/graywolf/gbook/issues/3"}}}

**Comment by coachshea** [comment]
That's great, thank you.

**Comment by graywolf** [comment]
Hm it works fine for me over here. Could you possibly try to delete keys `access_token` and `refresh_token` (should be last two) from your config file?

**Comment by coachshea** [comment]
I just tried running it again and it seems to be working fine. I tried it several times yesterday and kept getting the same message that I sent to you. Is there any chance that this was just a temporary google problem and nothing to do with gbook? If that's the case, I'm sorry that I bothered you, but I did try the website yesterday and it appeared to be working fine from the browser. 

--
John Shea
Head Football Coach
Spaulding High School
Cell:  617-605-5763
Email:  coachshea@fastmail.com

**Comment by graywolf** [comment]
It's possible that it was issue on Google's end. It's also very well possible that it was all according to they documentation and I just overlooked something when I wrote this :)

If the issue comes back, ping me here again and I'll try to react faster in order to also get hit by it.

Closing for now.
